#!/usr/bin/env python

import roslib; roslib.load_manifest('dofsliders')
from dofsliders import dsmain
import gtk

gtk.gdk.threads_init()
gtk.gdk.threads_enter()
app = dsmain.DOFSlidersMain()
gtk.main()
gtk.gdk.threads_leave()

